// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW2k1X1w584d6PHOlW_Y1GwR0u-efRqZw',
    appId: '1:462365261662:web:d1ea52d4d47c0d582b99cf',
    messagingSenderId: '462365261662',
    projectId: 'sql-auto-grader',
    authDomain: 'sql-auto-grader.firebaseapp.com',
    storageBucket: 'sql-auto-grader.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxquyxXuTHPv2Zv8GbIAvhBYoiVOz4oEE',
    appId: '1:462365261662:android:202abfd929bd48ec2b99cf',
    messagingSenderId: '462365261662',
    projectId: 'sql-auto-grader',
    storageBucket: 'sql-auto-grader.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn1OMAx4HKbwktTbZB7zwJg2pF89-eaTU',
    appId: '1:462365261662:ios:d00b41b4327eaf152b99cf',
    messagingSenderId: '462365261662',
    projectId: 'sql-auto-grader',
    storageBucket: 'sql-auto-grader.firebasestorage.app',
    iosBundleId: 'com.example.sqlAutoGrader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn1OMAx4HKbwktTbZB7zwJg2pF89-eaTU',
    appId: '1:462365261662:ios:d00b41b4327eaf152b99cf',
    messagingSenderId: '462365261662',
    projectId: 'sql-auto-grader',
    storageBucket: 'sql-auto-grader.firebasestorage.app',
    iosBundleId: 'com.example.sqlAutoGrader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW2k1X1w584d6PHOlW_Y1GwR0u-efRqZw',
    appId: '1:462365261662:web:ee32b5baee3004bc2b99cf',
    messagingSenderId: '462365261662',
    projectId: 'sql-auto-grader',
    authDomain: 'sql-auto-grader.firebaseapp.com',
    storageBucket: 'sql-auto-grader.firebasestorage.app',
  );
}
